Add files via upload
ElizaMejia/Proyecto-Mercado-Click pull request #1
Opened 2024-05-09 20:17 UTC by ElizaMejia

Se sube el proyecto con las observaciones hechas en el PR del repositorio de CSS

2024-05-10 15:33 UTC, semanticmx requested changes
hay que verificar que la página se vea bien ejecutando: `php -S 0.0.0.0:8081` desde la carpeta del proyecto y después navegando a `localhost:8081`

2024-05-10 15:33 UTC, semanticmx commented on index.html
> +
@ElizaMejia siguiendo la estructura propuesta, todos los CSS debe estar en la ruta assets/main.css

2024-05-10 15:33 UTC, semanticmx commented on index.html
> +<!DOCTYPE html>
Hay errores de validación de HTML con la etiqueta style

2024-05-10 15:33 UTC, semanticmx commented on index.html
> +                <img src="logo.png" alt="logo pagina web">
el logo se cambió de nombre pero no se movió a la carpeta assets y no existe en el repo

2024-05-16 17:50 UTC, ElizaMejia commented
@semanticmx  se crea un nuevo branch para corregir  y se cierra el presente

2024-05-16 17:50 UTC, closed without merging